### ISSUE TITLE
Updating Docker images at the same time as updating the Dockerfile

### ISSUE THREAD

**Issue by k1LoW** [ruby/ruby-docker-images#23]
Hi Team. Thanks for maintaining the images!

I would be very happy if you could update the Docker images provided by [ghcr.io](https://github.com/orgs/ruby/packages/container/package/ruby) and [Docker Hub](https://hub.docker.com/r/rubylang/ruby) along with the Dockerfile update (merge to base branch) of this repository.

I think it would have the following benefits.

- No more differences between the Docker images provided and the Dockerfile in this repository.
- The base Ubuntu image and packages will also be updated.

If you agree with the proposal, I can send you a pull request.

Specifically, I will use the `on.push` event and the build matrix

```yaml
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ...
      include:
        ...
```
